Add crystvis features #12
muon-spectroscopy-computational-project/muon-galaxy pull request #25
Opened 2022-11-30 14:56 UTC by patrick-austin

Closes #12 
This adds support for relevant crystvis features through the Galaxy UI.
![image](https://user-images.githubusercontent.com/61705287/204827229-05c5fe50-98d1-4242-b414-3022fc927104.png)

Note that the export screenshot will only output a blank image.

## How to test the changes?
(Select all options that apply)
- [ ] I've included appropriate [automated tests](https://docs.galaxyproject.org/en/latest/dev/writing_tests.html).
- [ ] This is a refactoring of components with existing test coverage.
- [x] Instructions for manual testing are as follows:
  1. Login
  2. Open visualisations
  3. Select crystvis, and chose a cell or cif file
  4. Test features work as expected, and labels make sense

## License
- [x] I agree to license these and all my past contributions to the core galaxy codebase under the [MIT license](https://opensource.org/licenses/MIT).

2022-12-05 10:13 UTC, joelvdavies requested changes
Just a minor typo, a suggestion and some questions about the format in general.

2022-12-05 10:13 UTC, joelvdavies commented on config/plugins/visualizations/crystvis/config/crystvis.xml
> +            <cases>
I assume this is correct but just wondered why there is a \<cases> within another \<cases> tag, and similarly with the \<inputs>.

2022-12-05 10:13 UTC, joelvdavies commented on config/plugins/visualizations/crystvis/config/crystvis.xml
> +            <test_param>
More of a question about muon galaxy but what are these test_params's for, it seems to be what is actually displayed but if that's the case what are the two lines above defining?

2022-12-05 10:13 UTC, joelvdavies commented on config/plugins/visualizations/crystvis/config/crystvis.xml
> +                            <help>All atoms with a co-ordinates between the start and end values will be returned, co-ordinates should be space separated</help>
Minor typo - could do without the 'a'. Also perhaps 'returned' should be 'displayed' in this context?

2022-12-05 10:13 UTC, joelvdavies commented on config/plugins/visualizations/crystvis/config/crystvis.xml
> +                            <help>All atoms within radius of the start value will be returned, co-ordinates should be space separated</help>
Same comment about returned.

2022-12-05 13:31 UTC, joelvdavies approved these changes
Looks good to me.

2023-01-09 10:36 UTC, patrick-austin commented
Regarding the failing tests: after syncing with the latest upstream code, [Mulled Unit Tests / Test (3.7)](https://github.com/galaxyproject/galaxy/actions/runs/3647908944/jobs/6160693185), [Test Galaxy packages / Test (3.7)](https://github.com/galaxyproject/galaxy/actions/runs/3647908932/jobs/6160692693), and [Test Galaxy packages / Test (3.10)](https://github.com/galaxyproject/galaxy/actions/runs/3647908932/jobs/6160692810) are all failing upstream in the 22.05 release branch. The cause of `Build docs / build (3.7)` failure is documented in #27

2023-01-17 12:04 UTC, merged